[build]
target = "riscv32ec_zmmul-unknown-none-elf.json"

[unstable]
build-std         = ["core"]
json-target-spec  = true

[env]
DEFMT_LOG = "trace"

[target.riscv32ec_zmmul-unknown-none-elf]
# probe-rs fork auto-detects WCH parts; no --chip needed.
runner = "probe-rs run"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
]
