[default.general]
chip = "STM32F301K8Ux"

[default.rtt]
enabled = true
timeout = 3000

log_enabled = true
log_path = "logs"

up_channels = [
 { channel = 0, mode="NoBlockSkip", format = "Defmt", file = "log.txt" },
 { channel = 1, mode="NoBlockSkip", format = "String", show_timestamps = false },
]

down_channels = [
    { channel = 0, mode="NoBlockSkip", format = "String" },
]

# Channel 0: REPL interactive (up + down paired)
# Channel 1: defmt logging (up only)
tabs = [
    { up_channel = 0, name = "Log" },
    { up_channel = 1, down_channel = 0, name = "Terminal" },
]

[default.reset]
halt_afterwards = false

[default.flashing]
enabled = true

[default.gdb]
enabled = false
